### ISSUE TITLE
CI builds failing due to lack of JavaFX

### ISSUE THREAD

**Issue by RDIL** [hyperiumjailbreak/LibInstaller#2]
Our codebase depends on JavaFX, which isn't in the `gradle` docker container.  

I tried installing it via `apt-get`, but that sadly didn't work either.

I have deleted it until we can find a solution.

/cc @fkorotkov

**Comment by RDIL** [comment]
Hey @fkorotkov can you please take a look at this when you can

**Comment by fkorotkov** [comment]
You can try to use a container like this: https://github.com/JabRef/docker-javafx And use Gradle wrapper to run the build.

**Comment by RDIL** [comment]
I literally just tried that haha, it didn't work :(

**Comment by fkorotkov** [comment]
`platpus/javafx` is two years old

**Comment by RDIL** [comment]
Need to give it a try 🤷‍♂

**Comment by fkorotkov** [comment]
Actually it worked. 🤷‍♂

**Comment by RDIL** [comment]
Yeah I just saw that 🤣

**Comment by RDIL** [comment]
I've rebuilt it with a newer openjdk version at https://cloud.docker.com/repository/docker/jumbocakeyumyum/jfx/general

Thanks for all your help!

**Comment by RDIL** [comment]
It works.  I'm not going to question why it now doesn't want to build.
